# Generated by Django 4.0 on 2021-12-11 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('resturant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('rest_type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30)),
                ('opens_at', models.CharField(max_length=30)),
                ('closes_at', models.CharField(max_length=30)),
                ('resturant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.resturant')),
            ],
        ),
    ]
